export const optionItem = {
  language: [
    'sql',
    'bigquery',
    'db2',
    'db2i',
    'hive',
    'mariadb',
    'mysql',
    'n1ql',
    'postgresql',
    'plsql',
    'redshift',
    'singlestoredb',
    'snowflake',
    'spark',
    'sqlite',
    'transactsql',
    'tsql',
    'trino',
  ],
  keywordCase: ['preserve', 'upper', 'lower'],
  dataTypeCase: ['preserve', 'upper', 'lower'],
  functionCase: ['preserve', 'upper', 'lower'],
  identifierCase: ['preserve', 'upper', 'lower'],
  indentStyle: ['standard', 'tabularLeft', 'tabularRight'],
  logicalOperatorNewline: ['before', 'after'],
  database: [
    'bigquery',
    'db2',
    'hive',
    'mariadb',
    'mysql',
    'postgresql',
    'transactsql',
    'flinksql',
    'snowflake',
  ],
}
